version: "3"
services:
  postgresql-test:
    image: kartoza/postgis:9.4-2.1
    command: sh -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/9.4/main/pg_hba.conf && /start-postgis.sh"
    ports:
      - "25432:5432"
    volumes:
      - ./data/postgresql-test:/var/lib/postgresql
